[package]
name = "mado_template"
version = "0.1.0"
edition = "2021"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crate_that_i_break_sometimes_for_testing = "0.1.0"
